### ISSUE TITLE
HTTPSConnectionPool

### ISSUE THREAD

**Issue by ephedan** [EchterAlsFake/Porn_Fetch#12]
Good morning.

I am contacting you to inform you that I often encounter the following error when downloading:
"Segment `72` failed: HTTPSConnectionPool(host='dv-h.phncdn.com', port=443): Max retries exceeded with url: /hls/videos/202203/01/403895761/1080P_8000K_403895761.mp4/seg-72-v1-a1.ts?ttl=1697661737&l=0&ipa=82.64.80.34&hash=5b041f20145cdce36375f15410dc178d (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Retrying to fetch 33 segments".

For information, I set the speed setting to "Usual". It doesn't change anything.

**Comment by EchterAlsFake** [comment]
The segment retrying isn't a problem. You just need to wait a bit and then it should work. If it really persists over like 1-2 minutes, you can reopen the issue.  It's btw. an issue from PornHub because downloading from their site isn't intended of course xD
