### ISSUE TITLE
Output Path

### ISSUE THREAD

**Issue by ephedan** [EchterAlsFake/Porn_Fetch#13]
Good morning.
I am contacting you to inform you that I often encounter the following error.
When in "Output Path" I enter "D:\Personnel\Documents", the files are downloaded to "D:\Personnel".
If I put "D:\Personal", the files are downloaded to "D:\".

I am using Windows version 2.9.

**Comment by EchterAlsFake** [comment]
Okay I'll look on my Windows machine to reproduce that. I am doing all my tests on Linux, so Windows is not my focus, but I'll try to fix it :)

**Comment by EchterAlsFake** [comment]
Should be fixed now. The problem was that I forgot to check if the user entered a / or \ after the path. Now Porn Fetch checks that automatically and appends it. 

Thanks for reporting :)
