### ISSUE TITLE
translation:en-us to zh-cn and one suggestion

### ISSUE THREAD

**Issue by Joshua-auhsoj** [EchterAlsFake/Porn_Fetch#17]
here is the Chinese translation file
[en-us to zh-cn.zip](https://github.com/EchterAlsFake/Porn_Fetch/files/14017801/en-us.to.zh-cn.zip)
I use some translations from cn. prefix pornhub page

and one suggestion: could you please sort the video number in reverse? Make the mode’s first video numbered with 001，and the newest video has the biggest number, thank you very much🥰

here is the code I got form ChatGPT
```python
    for i, video in enumerate(reversed(list(iterator)), start=1):
          item = QTreeWidgetItem(tree_widget)
          item.setText(0, f"{i}) {video.title}")
          item.setData(0, QtCore.Qt.UserRole, video.url)
          item.setCheckState(0, QtCore.Qt.Unchecked)  # Adds a checkbox
    ```

**Comment by EchterAlsFake** [comment]
Yeah I can do that, give me some hours xD

Just one thing for the chinese translations. When the final V3 version is out there are probably some changes on the ui and you'd need to update it, but I'll take your translations for now :)

Thanks.

**Comment by Joshua-auhsoj** [comment]
> Yeah I can do that, give me some hours xD
> 
> Just one thing for the chinese translations. When the final V3 version is out there are probably some changes on the ui and you'd need to update it, but I'll take your translations for now :)
> 
> Thanks.

Thank you,I will update it when V3 is out🥰

**Comment by EchterAlsFake** [comment]
So you now have a checkbox at the top of the treewidget. If it's checked the videos will be shown in reverse. I think this is the best solution.

The chinese translations are also integrated. I keep this issue still open and I'll ping you when the UI is finished, so that you can update the translations for the final state :)

Thanks.

**Comment by EchterAlsFake** [comment]
@Joshua-auhsoj 

The UI is now finished and you can now finalize your translations.

Please make sure to also translate the QCoreApplication.

![image](https://github.com/EchterAlsFake/Porn_Fetch/assets/106493918/236e6ee1-9ec9-40ba-b350-af1c700bf066)


Thanks :)

**Comment by Joshua-auhsoj** [comment]
> @Joshua-auhsoj
> 
> The UI is now finished and you can now finalize your translations.
> 
> Please make sure to also translate the QCoreApplication.
> 
> ![image](https://private-user-images.githubusercontent.com/106493918/300213411-236e6ee1-9ec9-40ba-b350-af1c700bf066.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTk3MjgsIm5iZiI6MTcwNjM5OTQyOCwicGF0aCI6Ii8xMDY0OTM5MTgvMzAwMjEzNDExLTIzNmU2ZWUxLTllYzktNDBiYS1iMzUwLWFmMWM3MDBiZjA2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QyMzUwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQzNmRkNzc1MDZhYTVhOWU2YjkxNDk4ODI2MGE5MDAyYmEzZDE1N2ViMDQ3MjRkMGU5ODc1NjM3Mjg4NjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UGrXT9lUWTOQcC9De_acitGM9RcTQ8UhXR_CHT1UFHw)
> 
> Thanks :)

OK，I will do it today🥰

**Comment by Joshua-auhsoj** [comment]
> @Joshua-auhsoj
> 
> The UI is now finished and you can now finalize your translations.
> 
> Please make sure to also translate the QCoreApplication.
> 
> ![image](https://private-user-images.githubusercontent.com/106493918/300213411-236e6ee1-9ec9-40ba-b350-af1c700bf066.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTEzMzIsIm5iZiI6MTcwNjQxMTAzMiwicGF0aCI6Ii8xMDY0OTM5MTgvMzAwMjEzNDExLTIzNmU2ZWUxLTllYzktNDBiYS1iMzUwLWFmMWM3MDBiZjA2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwMzAzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGY4ZTVmMTAwMTgzMzlkZThjOGIwZDdkNGU1M2I4MDU2YTRlMWIwMDNhODNmYTRiMmVlM2NhZWY1MWE0ODYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aeIStGjWVk1-3AUElAa5l2lQQzSmbLlbhLsq8XoxTRw)
> 
> Thanks :)

I finished it ，including the QCoreAppliation

[en to zh.zip](https://github.com/EchterAlsFake/Porn_Fetch/files/14074752/en.to.zh.zip)

**Comment by EchterAlsFake** [comment]
Thank you very much :)
