### ISSUE TITLE
FFmpeg downloading

### ISSUE THREAD

**Issue by xmuffinx** [EchterAlsFake/Porn_Fetch#21]
When trying to download with ffmpeg enabled this error appears

Traceback (most recent call last):
  File "main.py", line 325, in run
  File "phub\objects\video.py", line 242, in download
  File "phub\modules\download.py", line 104, in FFMPEG
TypeError: sequence item 8: expected str instance, WindowsPath found

**Comment by EchterAlsFake** [comment]
Oh, I forgot to make a string conversion. I'll update the PHUB module or do a string conversion. I'll fix that later, thanks for pointing it out :)

**Comment by EchterAlsFake** [comment]
Issue is fixed. V3.1 binary will contain the fix. If you want to use ffmpeg now, you need to use the python version from this repo.
