### ISSUE TITLE
Playlist limit?

### ISSUE THREAD

**Issue by RonLar1132** [EchterAlsFake/Porn_Fetch#26]
There seems to be a max of 50 videos? Result limit only goes up to 200? Up limit to 1000?

**Comment by EchterAlsFake** [comment]
I didn't think that anyone will ever need this, but I mean it's of course possible. I've changed the max allowed result to 2000. I don't want to compile it all again, as it's really time consuming.

In the folder where Porn Fetch is, there should be a file named "config.ini"

Edit this file and there you should see a "search_limit ="
After the = sign, just write your needed limit, like 1000. The GUI will still show 200, but when you actually search for videos or use the playlist it will take the value from the config file.

V3.2 won't have restrictions on this anymore.
