### ISSUE TITLE
Allow for custom attempt limit

### ISSUE THREAD

**Issue by RonLar1132** [EchterAlsFake/Porn_Fetch#28]
`WARNING:phub.core:Call failed: ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))). Retrying (attempt 1/4)`

the attempts are 4, before it aborts. There should be an option to allow for custom attempt limit.

**Comment by EchterAlsFake** [comment]
Should be done

But  if you get blocked anyways a higher retry limit won't fix an IP rate limit :D
