### ISSUE TITLE
When getting the videos from a playlist, sometimes not all videos are fetched

### ISSUE THREAD

**Issue by RonLar1132** [EchterAlsFake/Porn_Fetch#30]
if a playlist has number (x) videos, it may return far less than this number

**Comment by EchterAlsFake** [comment]
I'll fix the issues with the playlist, but it may take some weeks, as school starts again tomorrow and I have a lot to do there. I won't be developing the next week. Anyways, thanks for your reports.

**Comment by EchterAlsFake** [comment]
I updated the PHUB module and I tested it with a playlist with 700 videos and all 700 videos were loaded successfully and displayed in the correct order. I will now close the playlist issues. If you need this feature now, compile Porn Fetch from scrach and use git+https://github.com/EchterAlsFake/PHUB when installing the requirements. V3.2 will continue the updated PHUB version :)
