### ISSUE TITLE
Fail to fetch PH model videos (Rgegex  <get_flash> failed)

### ISSUE THREAD

**Issue by Hitman47** [EchterAlsFake/Porn_Fetch#33]
Hello,

When I try to find all videos of a specific PH model, I enter the model URL (https://www.pornhub.com/model/XXX) and click to find videos, but the program fails after 19 videos.

I tried with 5 models, and that always fails at 19...

Here's the error : 
2024-03-08 11:13:39.950434 : ←[96m[DEBUG] : ←[38;2;255;66;0m : Search Limit: 50 ←[0m
Pattern <get_flash> failed
Traceback (most recent call last):
  File "main.py", line 253, in run
  File "main.py", line 219, in process_video
  File "functools.py", line 995, in __get__
  File "phub\objects\video.py", line 575, in author
  File "phub\objects\user.py", line 103, in from_video
  File "phub\objects\video.py", line 131, in fetch
  File "phub\modules\parser.py", line 33, in resolve
  File "phub\consts.py", line 95, in wrapper
  File "phub\consts.py", line 60, in _throw_re_error
phub.errors.RegexError: Regex <get_flash> failed.

**Comment by EchterAlsFake** [comment]
Hi, this is a blocking mechanism from PornHub. We (the PHUB developers) are aware of this issue, but the problem for this is a little bit deeper so we weren't able to fix it yet. Please use the "get only title" option in the tree widget. This prevents the issue from happening.

I leave this issue open and let you know when it's fixed, but I don't even know if we ever even be able to fix it.

**Comment by EchterAlsFake** [comment]
So to give you a little update. We figured out, that the challenge resolver is broken. If you send a lot of requests PornHub will block your IP for a certain times and then errors like the one above happen. If we can fix the challenge resolver this should be fixed. We already did a short approach. If you want you can compile Porn Fetch with pyinstaller and try to use that. It will automatically use the new fixes from the PHUB package.

**Comment by Hitman47** [comment]
Wow, thank you very much for the update !
I will try as soon as possible, thanks.

**Comment by EchterAlsFake** [comment]
Okay fixed it. 

Just if you wonder, our logic for fixing the challenge was correct but we solved the challenge soo fucking fast that PornHub didn't accept that so we needed to make a short delay of 2 seconds. Will be implemented in V3.2  :)

**Comment by Hitman47** [comment]
Amazing, thanks !

That's interesting, I'm sure the delay won't be problematic.

I look forward to test the v3.2, then 😉

**Comment by EchterAlsFake** [comment]
So with the new PHUB commit we totally fixed all issues regarding videos. I  close this issue now as it shouldn't happen anymore. If it still does, please reopen it. 

Thank you for your time :)
