### ISSUE TITLE
[Feature Requests] Sort by duration

### ISSUE THREAD

**Issue by efraxs** [EchterAlsFake/Porn_Fetch#37]
Hello ill like to be able to sort by duration and have some options when i use select like more than X time Duration and first or last X

**Comment by EchterAlsFake** [comment]
Thanks for your ideas. I'll implement them the next days and let you know when it's done :)

**Comment by EchterAlsFake** [comment]
So I've implemented it now.

The time sorting works now by checking the checkbox at the top of the tree widget. After that sorting is enabled for the length, title and author. Just click on the length to sort from lowest -> maximum and click again to reverse it.

The range selecting now works by clicking the button "Select a range of videos". It will open another widget with two boxes, where you can specify the start end the end. All videos between this will be checked.

Thanks for your idead. I've added you into the credits. Have an awesome day :)

**Comment by EchterAlsFake** [comment]
Update:

So I now implemented your original approach xD. You can use the range selector and apply a starting time and an end time. All videos between that will be checked.

I hope this is how you wanted it to be :) 


Maybe you can test it out and tell me if I should change thins or if it's okay as it is.

**Comment by efraxs** [comment]
It looks good just a lil confusing how to check time but i know it will be optimize in future updates

**Comment by EchterAlsFake** [comment]
Thanks for your feedback. I'll make it simpler in the next release :)

**Comment by EchterAlsFake** [comment]
So as of now I would say that the automated selection based on patterns work very well. It may not look perfect but I think everyone should understand it after 1 minute of reading. I will close this issue now. However, if you have any additional feedback or improvements you can of course let me know about it. 

Thanks!
