### ISSUE TITLE
Error getting Phub playlist

### ISSUE THREAD

**Issue by efraxs** [EchterAlsFake/Porn_Fetch#39]
when i try to get a Phub playlist i get the following error 
```
 File "C:\Users\efrax\AppData\Local\Temp\ONEFIL~1\main.py", line 1620, in start_playlist
AttributeError: 'Playlist' object has no attribute 'videos'. Did you mean: 'views'?
```

Im in 3.3 version

**Comment by EchterAlsFake** [comment]
Fix will be in V3.4, thanks for reporting :) 

If you need this feature now, please run it from the source of this repository.

Have a wonderful day ^^
