### ISSUE TITLE
Unsupported Distribution notice on Arch-based distros

### ISSUE THREAD

**Issue by omar-st** [EchterAlsFake/Porn_Fetch#46]
Currently the installer gives a notification of "unsupported distribution" on EndeavourOS (which I use) based on the operating system name being "endeavouros" instead of "arch linux". However, this software would definitely also build successfully on other Arch-based distros.

My suggestion is that it case match the names of EndeavourOS, Manjaro, Garuda, and any other common Arch-based distros to be "arch linux". This is probably also the case for Ubuntu-based distros (Kubuntu, Mint, PopOS, etc), and other distros where the upstream is supported but downstream uses a different host name.

I can confirm that the repo builds fine on a vanilla arch VM, so I know it would also work on my EndeavourOS machine. Fundamentally, I think the best solution is not to query if the OS is named "arch linux" but to query if *the package manager* is pacman, but just case matching the distro name would resolve my issue.

**Comment by EchterAlsFake** [comment]
Thanks, I'll fix that on Sunday

**Comment by omar-st** [comment]
Thank you, I'll look out for it :)

**Comment by omar-st** [comment]
Hi, I wanted to check if there are any changes relating to this?

**Comment by EchterAlsFake** [comment]
(See my comment on your Pull request)

**Comment by omar-st** [comment]
Thanks! I think the recent merges fully resolve the issue I had.
