### ISSUE TITLE
Question about the tests

### ISSUE THREAD

**Issue by Egsagon** [EchterAlsFake/Porn_Fetch#5]
Hi,
In your test file you point out that with a delay of .2 seconds, the client crashes.
I haven't been able to replicate the error, mass downloading with no delay works fine for me. Can you provide a traceback?

Also, video.hotspots are now a map object. You can get them back to a list by generating them :)

**Comment by EchterAlsFake** [comment]
Hi,

1) When settings the delay to 0.2 or disabling it I had the problem, that after a while the connection just hang. So there was no error but the progressbar got stuck and it needed a real long time to continue and with 0.3 I didn't had that. But maybe was just luck or something. I also don't plan to implement this later.


2) Yes just stupid from me lol, thanks xD

**Comment by Egsagon** [comment]
Its more likely to be a PHUB error if it did not happen with PHUB3.
It might be because the segment url expire, i'll try to fix that.

**Comment by Egsagon** [comment]
I'm not sure yet, bu i believe the default download backend is too dummy and detected by ph limit rate.
I've implemented a FFMPEG download function which handles downloading way faster and more reliably. You can implement it like so:

```py
import phub

video = ...

video.download(..., downloader = phub.download.FFMPEG)
```
