### ISSUE TITLE
use on ubuntu

### ISSUE THREAD

**Issue by lolbroek-droid** [EchterAlsFake/Porn_Fetch#55]
how should i use it on ubuntu? i installed it but idk how to use it

**Comment by EchterAlsFake** [comment]
Hi,

After downloading the `PornFetch_Linux_GUI_x64.bin` file, you can right click on the file and it should say something like "Make this file executable" (or something similar). And then you can just double click on the file and Porn Fetch should open.

If that's not working, please go into a terminal and do: `chmod +x "filename"`
`chmod +x` makes an application executable

And then you could just do: `./filename.bin`

Hope that helps :)

**Comment by EchterAlsFake** [comment]
Hey,

since there is no response from you after two months, I assume that you could successfully start it and I will therefore close this issue now :)

**Comment by vista-man** [comment]
Ah yes sorry for not responding. and yes i got it to work

**Comment by lolbroek-droid** [comment]
Ah yes sorry for not responding. and yes i got it to work
