### ISSUE TITLE
The connection is terminated

### ISSUE THREAD

**Issue by matcha6666** [EchterAlsFake/Porn_Fetch#7]
版本：Porn_Fetch_2.7
网站：https://cn.pornhub.com/model/carrylight
I get an error after running，Not all of the retrieved videos are displayed.
The error message is as follows:
An error happened. This error will NOT be sent tosentry, to prevent leakingyour account data! ERROR:('Connection aborted.'ConnectionAbortedError（10053，‘你的主机中的软件中止了一个已建立的连接。None, 10053, None))

I thought the network was fluctuating and causing the error when I ran it again,A new error has occurred:
An error happened. Thiserror will NOT be sent to sentry, to prevent leaking
separated with n→
your account data! ERROR: HTTPSConnectionPoolchost=www.pornhub.comel
port-443): Max retries exceeded with url: /webmasters/video_by id?
n.pornhub.coiid=ph5b40ff9241d93 (Caused by SSLError(SSLEOFError 8,'ISSL:UD
UNEXPECTED EOF_WHILE READINGJ EOF occurred in violation of protocol
(ssl.c:1006))1)

**Comment by matcha6666** [comment]
An error happened. This error will NOT be sent to setry, to prevent leaking
your account data! ERROR: HTTPSConnectionPoolchost='www.pornhub.com
port=443): Read timed ouit. (read timeout= 30）

**Comment by matcha6666** [comment]
I think it's a problem of network fluctuations, and I change the network and seems to be okay again.

**Comment by EchterAlsFake** [comment]
Hi,

The first error, which you got:

(Caused by SSLError(SSLEOFError 8,'ISSL:UD
UNEXPECTED EOF_WHILE READINGJ EOF occurred in violation of protocol
(ssl.c:1006))1)

Is a problem with the SSL protocol. The SSL protocol is used to secure your connection. Since you are probably living in china (based on the symbols in your reports) I guess that it is a problem of the partially censored internet. I am not sure about that, but would be my first thought.

The second error with the read timeout is fixed in the next version (v2.8)

Have a wonderful day :)

**Comment by matcha6666** [comment]
Okay, I think you're right.
Can you add the function of quickly checking the retrieved videos, checking them one by one is a bit slow.

**Comment by EchterAlsFake** [comment]
Yes I can do that :)

**Comment by EchterAlsFake** [comment]
Done with: [c582352](https://github.com/EchterAlsFake/Porn_Fetch/commit/c5823529185175c368f3496fec8e41252603b54b)

**Comment by matcha6666** [comment]
> Done with: [c582352](https://github.com/EchterAlsFake/Porn_Fetch/commit/c5823529185175c368f3496fec8e41252603b54b)

How can I use your modified functionality to download the zip file in the code?

**Comment by EchterAlsFake** [comment]
You need to clone the repository, install the requirements and run the program.

Here's a short guide:

1) Install Python3 from https://python.org
2) Install Git

When installing python3 make sure that the option "Add to path" is checked.
When installing Git, leave everything on default, 

Open the windows CMD (or terminal) and enter the following:

git clone https://github.com/EchterAlsFake/Porn_Fetch
cd Porn_Fetch
pip install -r requirements.txt
python3 Porn_Fetch.py

(You may need to change the output path from settings).

This gives you the newest functionality, but is unstable and I can not guarantee for everything to work :) 

If you ran into any issues, I can simply create a pre-release for you and you can just use that.

**Comment by matcha6666** [comment]
> 您需要克隆存储库，安装需求并运行程序。
> 
> 这是一个简短的指南：
> 
> 1. 从 https://python.org 安装 Python3
> 2. 安装 Git for Windows
> 
> 安装 python3 时，请确保选中“添加到路径”选项。安装 Git 时，将所有内容保留为默认值，
> 
> 打开窗口 CMD（或终端）并输入以下内容：
> 
> Git clone https://github.com/EchterAlsFake/Porn_Fetch CD Porn_Fetch pip install -r requirements.txt python3 Porn_Fetch.py
> 
> （您可能需要从设置中更改输出路径）。
> 
> 这为您提供了最新的功能，但不稳定，我不能保证一切正常:)
> 
> 如果您遇到任何问题，我可以简单地为您创建一个预发布版本，您可以使用它。

Sure enough, something went wrong, haha
run python3 Porn_Fetch.py this instruction
Traceback (most recent call last):
  File "D:\Porn_Fetch\Porn_Fetch.py", line 18, in <module>
    from phub import Client, Quality, locals, errors  # See https://github.com/Egsagon/PHUB
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'locals' from 'phub' (D:\Python311\Lib\site-packages\phub\__init__.py)

**Comment by matcha6666** [comment]
Let's use version 2.7 first, and then use the new features when you improve it directly in version 2.8
